### ISSUE TITLE
Place screen shots in design issues

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#163]
- [x] #161 - Design search results page
- [x] #81 - Design the organizations page
- [x] #84 - Design the Howto page
- [x] #103 - Design User Settings page
- [x] #114 - Design the create/edit Help Request page
